import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/reset.css'
import './globals.css'

import { DefaultContent, DefaultFooter, DefaultHeader } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>

          <DefaultHeader />
          
          <DefaultContent>
            {children}
          </DefaultContent>
          
          <DefaultFooter />
        </body>
      
    </html>
  )
}
